## Singular value decomposition

In [1]:
import torch
import numpy as np
_ = torch.manual_seed(0)

#### Generate rank-deficient matrix
**Rank**: 

The rank of a matrix is the number of linearly independent rows (or columns) it contains. 

**Full Rank**:

A matrix has full rank if its rank is equal to the minimum of the number of rows and columns. 

**Rank-Deficient**:

A matrix is rank-deficient if its rank is less than the minimum of the number of rows and columns. 

In [3]:
d, k = 10, 10
W_rank = 2
W = torch.randn(d, W_rank) @ torch.randn(W_rank, k)     # '@' matrix multiplication operator in pytorch
print(W)

tensor([[ 2.8501, -4.1679, -1.2931, -1.7376, -2.5698, -3.2220, -1.4271, -1.2982,
          0.2702,  1.2163],
        [ 3.2737, -4.7411, -1.4644, -1.9621, -2.9216, -3.6760, -1.6166, -1.4949,
          0.2975,  1.3819],
        [-0.0141, -3.3560, -1.5177, -2.4550, -2.1852, -1.7979, -1.6433,  0.2801,
          0.9375,  1.1010],
        [-0.8365,  0.4910,  0.0490, -0.0243,  0.2776,  0.5523,  0.0609,  0.4404,
          0.1243, -0.1169],
        [-3.9740, -0.6857, -1.1295, -2.3176, -0.6460,  1.0025, -1.1858,  2.3367,
          1.4298,  0.4341],
        [ 0.7376, -0.9989, -0.2987, -0.3915, -0.6132, -0.7910, -0.3304, -0.3424,
          0.0478,  0.2886],
        [-2.2472,  1.8582,  0.3750,  0.3281,  1.0966,  1.7733,  0.4272,  1.1393,
          0.1840, -0.4908],
        [ 0.7821, -0.5984, -0.1087, -0.0790, -0.3502, -0.5912, -0.1251, -0.4004,
         -0.0775,  0.1550],
        [-0.0482, -0.4016, -0.1912, -0.3150, -0.2638, -0.1991, -0.2066,  0.0602,
          0.1267,  0.1342],
        [ 0.6151, -

In [ ]:
# Verify the rank of the matrix W

W_rank = np.linalg.matrix_rank(W)
print(f'Rank of W: {W_rank')

Rank of W: 2 


Calculate the Singular Value Decomposition(SVD) of the matrix W
https://pytorch.org/docs/stable/generated/torch.svd.html

In [7]:
# Perform SVD on W (W = UxSxV^T, where S is a diagonal matrix)
U, S, V = torch.svd(W)

# For rank-r factorization, keep only the first r singluar values (and corresponding values of U and V)
U_r = U[:, :W_rank]
S_r = torch.diag(S[:W_rank])
V_r = V[:, :W_rank].t()

A = V_r
B = U_r @ S_r

print(f'Shape of B is: {B.shape}')
print(f'Shape of A is: {A.shape}')

Shape of B is: torch.Size([10, 2])
Shape of A is: torch.Size([2, 10])


Given the same input, check the output using original W and the matrices resulting from the decomposition

In [12]:
bias = torch.randn(d)
x = torch.randn(d)

y = W @ x + bias

y_hat = (B @ A) @ x + bias

print('Original y using W:\n', y)
print('\ny_hat computed using BA:\n ',y_hat )

Original y using W:
 tensor([ 2.2160,  0.6968,  0.6303, -0.9141,  0.3327,  1.2159,  0.6038, -0.5784,
        -0.7409,  2.1185])

y_hat computed using BA:
  tensor([ 2.2160,  0.6968,  0.6303, -0.9141,  0.3327,  1.2159,  0.6038, -0.5784,
        -0.7409,  2.1185])


In [13]:
print('Total parameters of W:', W.nelement())
print('Total parameters of A and B:', A.nelement() + B.nelement())


Total parameters of W: 100
Total parameters of A and B: 40
